### ISSUE TITLE
Umm... how do I fire this up??

### ISSUE THREAD

**Issue by dstroot** [appsforartists/ambidex#3]
Obviously this isn't it...  :)

```
$ node Ambidex.server.js
/Users/Dan/Code/ambidex/src/Ambidex.server.js:15
                            (path) => {
                                   ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by dstroot** [comment]
Never mind I found the bike example from the video...
